site_name: Museoviraston QField-pilotti
site_url: https://gispocoding.github.io/museovirasto-qfield/
copyright: 'Tekijä: <a href="info@gispo.fi">Gispo Suomi Oy.</a>'
nav:
  - Koti: 0_index.md
  - Alkuvalmistelut: 1_alkuvalmistelut.md
  - Projektin vienti QFieldiin: 2_vienti.md
use_directory_urls: false
theme: readthedocs